### ISSUE TITLE
Feature Request: Don't show "filter by email" until my contacts are loaded

### ISSUE THREAD

**Issue by philrenaud** [nylas/components#104]
Over on https://components.nylas.io/components/contact-list/src/index.html, the "Filter by Email" input and prompt show up before contacts are loaded. We should only show this if there are any contacts to filter.

![CleanShot 2021-10-04 at 10 13 34](https://user-images.githubusercontent.com/713991/135867059-112ad395-0a00-41e1-b189-ca7ce8e2a6b8.png)

**Comment by fastboot** [comment]
Hey can I fix this? Assign it to me

**Comment by AaronDDM** [comment]
> Hey can I fix this? Assign it to me

Yes, go for it!

**Comment by AaronDDM** [comment]
Hey @fastboot - are you still interested on working on this issue?

**Comment by AaronDDM** [comment]
Awesome! When you are ready with your changes, please make a PR in line with our [contributing guidelines](https://github.com/nylas/components/blob/main/CONTRIBUTING.md)!
