### ISSUE TITLE
[BUG] Nylas Email Component Rendering Issues / Performance

### ISSUE THREAD

**Issue by PranavSathy** [nylas/components#171]
**Describe the bug**
Leveraging the `Email` component for any thread results in a **huge** whitespace between messages.

**To Reproduce**
Send emails back and forth through Outlook Web , open the thread in Nylas Email component. There will be jumbled text and large white spaces.

**Expected behavior**
It renders cleanly, without large whitespace and without affecting parent container CSS.

**Version:**
1.0.13

**Additional context**
See video below:

https://drive.google.com/file/d/12aGtAaeER9ZioCQ3cOEHwNdvmiIkBJdF/view?usp=sharing

**Comment by PranavSathy** [comment]
Just curious if there is an ETA here and https://github.com/nylas/components/issues/172? Both are blocking our ability to integrate this component successfully.

**Comment by PranavSathy** [comment]
Thanks Oliver, unfortunately we don't have the bandwidth to roll a minimal reproducible at the moment :( [swamped on other things]. Recommendation would be a simple NextJS boilerplate application and render a hard coded Nylas email to see if it can be repro'ed.

I can see if the team can put together a repro earlier next week otherwise.

**Comment by ozsivanov** [comment]
@PranavSathy I pushed v1.0.14 with fixes for both issues included. Please re-open if you're still running into these bugs.

**Comment by PranavSathy** [comment]
@ozsivanov Awesome, thanks for these fixes. Had a minute to test out 1.0.14 on my Feature branch, looks like both of the issues mentioned here and in #172 were fixed. I noticed one last issue, which I will now as a bug.
