### ISSUE TITLE
Query params from url are being added to request query params 

### ISSUE THREAD

**Issue by logblythe** [nylas/components#177]
While making the request to get the threads, the query params from url are being added to the request query params. This results in failure of the request. 
Attacehd the screenshot showing the error response.

![image](https://user-images.githubusercontent.com/29378822/140746474-c448e949-b9e3-4c0b-9d59-2a26a43114d8.png)

***Version***
1.0.13

**Comment by philrenaud** [comment]
Hi @logblythe! Thanks for bringing this to our attention; we'll work on getting this fixed immediately.

**Comment by pooja169usp** [comment]
Hey @logblythe, 
We have pushed v1.0.14 with a fix for this issue. Please re-open if you're still running into this.

Thank you!
