### ISSUE TITLE
[BUG] Nylas Email Thread Overflows Container Width

### ISSUE THREAD

**Issue by PranavSathy** [nylas/components#183]
**Describe the bug**
We render email threads in our application as a "flyout" which is a few hundred pixel pane attached to the right side of our application. Sometimes, large email threads rendered in `nylas-email` seems to cause an `overflow-x` scroll.

https://drive.google.com/file/d/1Tv6JFXFkMPFuj8SF80F11HqTrF9hCDXn/view?usp=sharing

**To Reproduce**
Create a fixed container on the right hand side of the page, with a width of 512 px. View a large email thread (> 20 messages, large paragraph responses).

**Expected behavior**
We expect the `nylas-email` component to honor the parent container's width and text-wrap neatly within the container (including whatever margins paddings we specify).

**Version:**
1.0.14

**Comment by pooja169usp** [comment]
@PranavSathy We have fixed this issue in this [PR](https://github.com/nylas/components/pull/187).
The fix will be available in a canary version that will be released today and a stable version will be released on Friday.

Thank you!

**Comment by PranavSathy** [comment]
Ah excellent thank you Pooja!

**Comment by PranavSathy** [comment]
Seems like this is still broke on Canary version `1.0.15-canary.1` for me.

**Comment by pooja169usp** [comment]
Hey @PranavSathy,
I'm not able to reproduce this on Canary version: `1.0.15-canary.1`.

This is what it looks like (with the width of the container set to: 512px):
![image](https://user-images.githubusercontent.com/16315004/141818973-a6c9da21-e9ec-4bc5-80c0-e2457aa0af55.png)

Could you please share some screenshots for additional context?

**Comment by philrenaud** [comment]
Hi Pranav, we have [a fix](https://github.com/nylas/components/pull/198) in the works for handling when messages have wider styles than the container. We can't condense internal email styles further, but we can add an overflow to make them scrollable. Take a look at the demo video that @pooja169usp put there and let us know if that won't work for you. 

Thanks as always for raising these issues with us -- it helps direct our efforts!

**Comment by PranavSathy** [comment]
Thank you @philrenaud / @pooja169usp , appreciate the work. Ya I believe it's because of the content of the container being so long, that being said, in the future would be great if it was possible to just linewrap/text-wrap but this is acceptable for our use case!
