### ISSUE TITLE
[BUG] "window is not defined" in non-browser context

### ISSUE THREAD

**Issue by AndrewCraswell** [nylas/components#212]
**Describe the bug**
Since the Nylas components are built with Svelte and compiled to Web Components, it can't be assumed that they are always being rendered in a strictly browser environment. For example, even a SvelteKit app will need to process the component on the Server Side, even if SSR is set to false.

In my case, I'm using the Agenda component in a SvelteKit app, and when executing `yarn build & yarn preview` the following error is received:

```
> window is not defined
ReferenceError: window is not defined
    at C:\Users\ajcra\Desktop\piste-web\node_modules\@nylas\components-agenda\index.js:1:244
    at C:\Users\ajcra\Desktop\piste-web\node_modules\@nylas\components-agenda\index.js:1:85
    at Object.<anonymous> (C:\Users\ajcra\Desktop\piste-web\node_modules\@nylas\components-agenda\index.js:1:205)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
error Command failed with exit code 1.
```

After examining the Agenda, I suspect it's because of this reference to `window`:
https://github.com/nylas/components/blob/main/commons/src/define-component-patch.ts

**To Reproduce**
This repo demonstrates the issue:
https://github.com/AndrewCraswell/piste-web/tree/u/andcra/nylas-ssr-bug

```
yarn build
yarn preview
```

**Expected behavior**
The components should be able to be referenced in a non-browser environment and should avoid calling browser specific APIs if they are not available.

**Version:**
`^1.0.14`

**Additional context**

**Comment by ozsivanov** [comment]
Hi @AndrewCraswell, thanks for identifying this! We've triaged this bug internally and should have a resolution later this week / early next week.

**Comment by ozsivanov** [comment]
Just an update - we've found the root cause of the issue but it requires a bit of a larger change to how we're registering web components vs svelte components internally. Once that change is made, we should be able to resolve this.

**Comment by krisgardiner** [comment]
@AndrewCraswell unfortunately we ran into some issues when attempting to fully support SSR.

In the meantime, you can import the components at runtime by importing them during svelte's `onMount` lifecycle method. Would look something like this:
```
onMount(async () => {
   await import('@nylas/component-mailbox');
});
```
