### ISSUE TITLE
yarn storybook fails from fresh clone/install

### ISSUE THREAD

**Issue by daveo1984** [nylas/components#218]
Brand new to this repo / code and just trying to do the most basic setup based on the readme. 

When running yarn storybook I get a long list of warnings and errors
I'm running a docker containers, tried node:14.0.0-buster and , node:14-buster (the latter comes with node v.14.18.1).  I long list of warnings and errors in the output (see attached)

[2021-11-23-error-output.txt](https://github.com/nylas/components/files/7591422/2021-11-23-error-output.txt)

Not a node dev so I could totally be doing something wrong, but not sure what I should be looking for.

**Comment by philrenaud** [comment]
Hey @daveo1984 , thanks for raising this. Use of storybook in this repo is a bit out of date; we'll be removing it in an update soon.

In the meanwhile, running `yarn start` after installation will yield a components page that includes many of the properties in a playground-like environment, like what storybook provides. Check out an example in the sidebar at https://components.nylas.io/components/availability/src/index.html .
