### ISSUE TITLE
Add Attachments support in Email component

### ISSUE THREAD

**Issue by himankbhalla** [nylas/components#227]
**Is your feature request related to a problem? Please describe.**
Currently email component does not support attachments. So when an email contains files as an attachment , it is simply ignored in the email component.

**Describe the solution you'd like**
The Nylas API response json contains the file related information, if the email contains an attachment. And there's another file API present. So we can use both of these to make the attachments downloadable, just like in any other provider client.

**Comment by AaronDDM** [comment]
Hey @himankbhalla, thanks for this feature request!

This is something we're working on for next week, so expect it in an upcoming release soon. We'll update this issue once it has been released.

Thank you!

**Comment by himankbhalla** [comment]
@AaronDDM  Thanks for the update. Will be looking forward to the next release. Can you give a rough estimation as to when I can expect that ?

**Comment by pooja169usp** [comment]
Hey @himankbhalla, 

We have release this feature in canary version `1.1.5-canary.0`, a stable release will follow soon. 

Thank you for your patience!

**Comment by pooja169usp** [comment]
Hey @himankbhalla, We have released this feature as part of following versions:
Email: v 1.1.5
Mailbox: v 1.1.4

Thank you!
