### ISSUE TITLE
Ability to reply in the same thread in email component

### ISSUE THREAD

**Issue by himankbhalla** [nylas/components#228]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to reply to an email thread via the mailbox component.

**Describe the solution you'd like**
The "Send a Message" API supports a reply_to and reply_to_message_id fields which can be used along with the compose component, to provide this reply to feature in the mailbox component.

**Comment by nickbair-nylas** [comment]
Hi @himankbhalla, thanks for reaching out.  Let's discuss this on our call tomorrow.

**Comment by femyeda** [comment]
Hi, @himankbhalla 

Quick update. There's a canary release that includes the reply functionality.

https://unpkg.com/@nylas/components-mailbox@1.1.6-canary.6/index.js
https://unpkg.com/@nylas/components-email@1.1.7-canary.4/index.js

A demo can be seen here. https://components.nylas.io/components/mailbox/src/index.html
