### ISSUE TITLE
Is there an option to listen to back button press?

### ISSUE THREAD

**Issue by logblythe** [nylas/components#277]
I went through the list of available event listeners over here
https://developer.nylas.com/docs/user-experience/components/mailbox-component/#mailbox-event-listeners

But couldn't find a way to listen to back button press. Is there such option?

**Comment by krisgardiner** [comment]
@logblythe thanks for checking out our docs! We currently don't have this feature but we can add it to the next release. We'll keep you posted when it's available.

**Comment by krisgardiner** [comment]
@logblythe After investigating, `returnToMailbox` is an event that is dispatched when the back button is clicked. https://github.com/nylas/components/blob/main/components/email/src/Email.svelte#L473. I'll be updating the docs with this event listener soon.
